---
sidebar: sidebar 
permalink: docs/hci_prereqs_network_switch.html 
summary: このバージョンの NetApp HCI の新機能について説明します。 
keywords: netapp, hci, network, switch, requirements 
---
= ネットワークとスイッチの要件
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
導入を成功させるためには、 NetApp HCI に使用するスイッチで特別な設定が必要になります。以降に記載するそれぞれの要件を環境に実装する手順については、使用するスイッチのドキュメントを参照してください。

NetApp HCI 環境には、次のトラフィックタイプごとに 1 つ、少なくとも 3 つのネットワークセグメントが必要です。

* 管理
* VMware vMotion
* ストレージ / データ


NetApp H シリーズのコンピューティングノードおよびストレージノードのモデルや計画しているケーブル構成に応じて、別々のスイッチを使用してこれらのネットワークを物理的に分離するか、または VLAN を使用して論理的に分離することができます。ただしほとんどの環境では、これらのネットワーク（およびその他の仮想マシンネットワーク）を VLAN を使用して論理的に分離する必要があります。

コンピューティングノードとストレージノードは、導入中およびその前後に通信可能である必要があります。ストレージノードとコンピューティングノードに別々の管理ネットワークを実装する場合は、それらの管理ネットワーク間にネットワークルートが確立されていることを確認してください。これらのネットワークにはゲートウェイが割り当てられている必要があり、ゲートウェイ間にルートが必要です。ノードと管理ネットワーク間の通信を確保するために、新しい各ノードにゲートウェイが割り当てられていることを確認してください。

NetApp HCI スイッチの要件は次のとおりです。

* NetApp HCI ノードに接続するスイッチポートは、すべてスパニングツリーのエッジポートとして設定する必要があります。
+
** Cisco スイッチでは、スイッチモデル、ソフトウェアバージョン、およびポートタイプに応じて、次のいずれかのコマンドを使用してこの操作を実行できます。
+
*** `spanning-tree port type edge`
*** `spanning-tree port type edge trunk`
*** `spanning-tree portfast`
*** `spanning-tree portfast trunk`


** Mellanoxスイッチでは、コマンドを使用してこの処理を実行できます `spanning-tree port type edge`。


* NetApp HCI ノードには、アウトオブバンド管理を除くすべてのネットワーク機能用に冗長なポートがあります。最大限の耐障害性を実現するには、これらのポートを 2 つのスイッチに分け、従来の階層型アーキテクチャまたはレイヤ 2 のスパイン / リーフ型アーキテクチャへの冗長なアップリンクを確保します。
* ストレージ、仮想マシン、 vMotion の各トラフィックを処理するスイッチは、ポートあたり 10GbE 以上の速度をサポートする必要があります（ポートあたり最大 25GbE がサポートされます）。
* 管理トラフィックを処理するスイッチは、ポートあたり1GbE以上の速度をサポートする必要があります。
* ストレージおよび vMotion のトラフィックを処理するスイッチポートには、ジャンボフレームを設定する必要があります。インストールを成功させるには、ホストが 9000 バイトのパケットをエンドツーエンドで送信できる必要があります。
* すべてのストレージノードとコンピューティングノードの間のラウンドトリップネットワークレイテンシが2ミリ秒を超えないようにする必要があります。


すべての NetApp HCI ノードは、専用の管理ポートを通じてアウトオブバンド管理機能を提供します。NetApp H300S、H300E、H500S、H500E、H700S、H700E、H410Cの各ノードでは、ポートAを介したIPMIアクセスも可能です。ベストプラクティスとして、環境内のすべてのノードに対してアウトオブバンド管理を設定することで、NetApp HCIのリモート管理を簡易化することを推奨します。

[discrete]
== 詳細情報

* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 向け NetApp Element プラグイン"^]

