---
sidebar: sidebar 
permalink: docs/task_hci_2noderepl.html 
summary: 2ノードクラスタに含まれるノードを交換する前に、最初に3つ目のストレージノード（新しいIPアドレスのセットが必要）を追加し、同期が完了してから、障害が発生したノードを削除する必要があります。4ノードクラスタ。追加の MIP と SIP が必要です。 
keywords: netapp, hci, H610C, H615C, chassis replacement, node replacement 
---
= 2 ノードクラスタのストレージノードを交換
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
2 ノードクラスタの一部であるストレージノードを交換する前に、最初に 3 つ目のストレージノード（新しい IP アドレスのセットが必要）を追加し、同期を完了させてから、障害ノードを削除してください。交換用ノードがクラスタに追加されるまで、クラスタはデグレード状態のままです。

.必要なもの
* 新しい管理 IP アドレスとストレージ IP アドレスを用意します。
* ノードがオフラインになったあとにクラスタにアラートが表示されることを確認しておき `ClusterCannotSync`ます。これにより、新しいノードがクラスタに再度追加されたときに、クラスタの完全な再同期が実行されます。このアラートは、ストレージノードがオフラインになってから約 6 分後に表示されます。
* NetAppサポートに連絡しておきます。交換用製品を注文する場合は、ネットアップサポートでケースをオープンする必要があります。
* 交換用ノードを入手します。
* 静電放電（ ESD ）リストバンドを装着するか、静電気防止処置を行っておきます。


.タスクの内容
VMware vSphere Web Client のアラームでは、ホストで障害が発生するとアラートが通知されます。VMware vSphere Web Client で障害が発生したホストのシリアル番号を、ノード背面のステッカーに記載されているシリアル番号と一致させる必要があります。

.手順
. 障害が発生したノードをラックから物理的に取り外します。実行する手順は、使用するストレージノードのタイプによって異なります。およびを参照してくださいlink:task_hci_h410srepl.html["H410S ノードを交換してください"]link:task_hci_h610srepl.html["H610S ノードを交換してください"]。
+

NOTE: この時点では、クラスタからノードを削除しないでください。

. 交換用ノードを同じスロットに設置します。
. ノードをケーブル接続
. ノードの電源をオンにします。
. キーボードとモニタをノードに接続
. 設定手順を実行します。
+
.. IPMI / BMC IP アドレスを設定します。
.. 新しい管理 IP アドレスとストレージ IP アドレス、およびクラスタ名を使用して新しいノードを設定します。


. ノードをクラスタに追加したら、ドライブを追加します。
. 同期が完了したら、障害が発生したドライブとノードをクラスタから削除します。
. NetApp Hybrid Cloud Control を使用して、追加した新しいストレージノードを設定します。を参照して link:task_hcc_expand_storage.html["NetApp HCI ストレージリソースを展開します"]




== 詳細情報

* http://docs.netapp.com/hci/index.jsp["NetApp HCIドキュメントセンター"^]
* http://docs.netapp.com/sfe-122/index.jsp["SolidFire と Element ソフトウェアドキュメントセンター"^]

