---
sidebar: sidebar 
permalink: docs/task_hcc_expand_compute.html 
summary: NetApp HCI の導入が完了したら、ネットアップハイブリッドクラウド制御を使用して NetApp HCI のストレージリソースを拡張および設定できます。 
keywords: netapp, hci, on premise, expand, compute, cluster 
---
= NetApp HCI コンピューティングリソースを展開します
:allow-uri-read: 


[role="lead"]
NetApp HCI の導入が完了したら、ネットアップハイブリッドクラウド制御を使用して NetApp HCI コンピューティングリソースを拡張および設定できます。

.必要なもの
* 分散仮想スイッチを使用している環境を拡張する場合は、 NetApp HCI の vSphere インスタンスで vSphere Enterprise Plus ライセンスが使用されていることを確認してください。
* NetApp HCI で使用しているすべての vCenter インスタンスと vSphere インスタンスでライセンス期間が終了していないことを確認しておきます。
* 既存のノードと同じネットワークセグメントに未使用の空いている IPv4 アドレスがあることを確認してください（新しいノードは、同じタイプの既存のノードと同じネットワークにインストールする必要があります）。
* vCenter 管理者アカウントのクレデンシャルを準備しておきます。
* 新しいノードごとに次の操作を実行しておきます。
+
** の手順に従って、NetApp HCIシャーシに新しいノードを設置しlink:task_hci_installhw.html["インストール手順"]ます。
** 新しいノードのケーブルを配線して電源をオンにします


* 新しいノードのネットワークトポロジとケーブル配線が既存のストレージクラスタまたはコンピューティングクラスタと同じであることを確認しておきます。


.手順
. Webブラウザで管理ノードのIPアドレスを開きます。例：
+
[listing]
----
https://<ManagementNodeIP>
----
. NetApp HCI ストレージクラスタ管理者のクレデンシャルを指定して NetApp Hybrid Cloud Control にログインします。
. インターフェイスの右上隅にある*[Expand]*を選択します。
+
ブラウザに NetApp Deployment Engine が表示されます。

. ローカルのNetApp HCIストレージクラスタ管理者のクレデンシャルを指定してNetApp Deployment Engineにログインします。
+

NOTE: Lightweight Directory Access Protocolのクレデンシャルを使用してログインすることはできません。

. [ようこそ]ページで*[はい]*を選択し、*[続行]*を選択します。
. [End User License]ページで、VMwareのエンドユーザライセンス契約を読み、*[I accept]*を選択して条件に同意し、*[Continue]*を選択します。
. vCenter * ページで、次の手順を実行します。
+
.. NetApp HCI 環境に関連付けられている vCenter インスタンスの FQDN または IP アドレスと管理者のクレデンシャルを入力します。
.. 「 * Continue * 」を選択します。
.. コンピューティングノードを追加するvSphereデータセンターを選択するか、*[Create New Datacenter]*を選択して新しいデータセンターにコンピューティングノードを追加します。
+

NOTE: [Create New Datacenter]*を選択すると、[Cluster]フィールドに値が自動的に入力されます。

.. 既存のデータセンターを選択した場合は、新しいコンピューティングノードを関連付ける vSphere クラスタを選択します。
+

NOTE: 拡張対象として選択したクラスタのネットワーク設定を NetApp HCI が認識できない場合は、管理、ストレージ、 vMotion ネットワーク用の VMkernel と vmnic マッピングが導入時のデフォルトに設定されていることを確認してください。詳細については、を参照してください link:task_nde_supported_net_changes.html["サポートされるネットワーク変更"] 。

.. 「 * Continue * 」を選択します。


. ESXi クレデンシャル * ページで、追加するコンピューティングノードの ESXi root パスワードを入力します。
+
NetApp HCI の初期導入時に作成したパスワードを使用する必要があります。

. 「 * Continue * 」を選択します。
. 新しい vSphere データセンタークラスタを作成した場合は、「 * ネットワークトポロジ * 」ページで、追加する新しいコンピューティングノードと一致するネットワークトポロジを選択します。
+

NOTE: ケーブル 2 本のオプションを選択するのは、コンピューティングノードがケーブル 2 本のトポロジを使用しており、既存の NetApp HCI 環境に VLAN ID が設定されている場合のみです。

. Available Inventory * ページで、既存の NetApp HCI 環境に追加するノードを選択します。
+

IMPORTANT: 一部のコンピューティングノードでは、 vCenter のバージョンでサポートされている最高レベルで EV を有効にしないと、インストール環境に追加できない場合があります。そのようなコンピューティングノードについては、 vSphere クライアントを使用して EVC を有効にする必要があります。有効にしたら、インベントリページをリフレッシュし、コンピューティングノードの追加をもう一度実行してください。

. 「 * Continue * 」を選択します。
. * オプション * ：新しい vSphere データセンタークラスタを作成した場合、 * ネットワーク設定 * ページで、既存の NetApp HCI 環境から * 既存のクラスタから設定をコピー * チェックボックスを選択してネットワーク情報をインポートします。
+
これにより、各ネットワークにデフォルトゲートウェイとサブネットの情報が設定されます。

. [* ネットワークの設定 * ] ページで、初期導入時に一部のネットワーク情報が検出されました。シリアル番号順に表示された新しいコンピューティングノードのそれぞれについて、新しいネットワーク情報を割り当てる必要があります。新しいコンピューティングノードごとに、次の手順を実行します。
+
.. * ホスト名 *: NetApp HCI が名前のプレフィックスを検出した場合は、 [ 検出された名前のプレフィックス *] フィールドから名前のプレフィックスをコピーし、新しいホスト名のプレフィックスとして挿入します。
.. * 管理 IP アドレス * ：管理ネットワークサブネットにある新しいコンピューティングノードの管理 IP アドレスを入力します。
.. * vMotion IP Address * ： vMotion ネットワークサブネット内の新しいコンピューティングノードに vMotion IP アドレスを入力します。
.. * iSCSI A-IP アドレス * ： iSCSI ネットワークサブネットにあるコンピューティングノードの最初の iSCSI ポートの IP アドレスを入力します。
.. * iscsi B-IP Address * ： iSCSI ネットワークサブネットにあるコンピューティングノードの 2 番目の iSCSI ポートの IP アドレスを入力します
.. 「 * Continue * 」を選択します。


. [ ネットワーク設定 ] セクションの [ * レビュー ] ページでは、新しいノードが太字で表示されます。セクションを変更するには、次の手順を実行します。
+
.. そのセクションの * 編集 * を選択します。
.. 完了したら、以降のページで* Continue *を選択して* Review *ページに戻ります。


. * オプション * ：ネットアップがホストする SolidFire Active IQ サーバにクラスタの統計情報とサポート情報を送信しない場合は、最後のチェックボックスをオフにします。
+
これにより、 NetApp HCI のリアルタイムの健常性診断の監視機能が無効になります。この機能を無効にすると、ネットアップによる NetApp HCI のプロアクティブなサポートと監視が行われなくなるため、本番環境が影響を受ける前に問題を検出して解決できなくなります。

. [ * ノードの追加 * ] を選択します。
+
リソースの追加と設定の進捗状況は、 NetApp HCI で監視できます。

. * オプション * ：新しいコンピューティングノードが VMware vSphere Web Client に表示されることを確認します。


[discrete]
== 詳細情報

* https://library.netapp.com/ecm/ecm_download_file/ECMLP2856176["NetApp HCI コンピューティングノードとストレージノードの設置とセットアップの手順"^]
* https://kb.vmware.com/s/article/1003212["VMware のナレッジベース：「 Enhanced vMotion Compatibility （ EVC ） processor support"^]

