---
sidebar: sidebar 
permalink: docs/task_nde_join_existing_vsphere.html 
summary: NetApp HCI の導入時に VMware vSphere を設定する方法について説明します。 
keywords: netapp, hci, netapp deployment engine, deployment, vsphere 
---
= 既存の VMware vSphere 環境に参加します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
vCenter Server のネットワーク情報とクレデンシャルを指定して、既存の vSphere 環境に NetApp HCI を導入するように設定します。

.必要なもの
* 既存の vSphere 6.7 の環境に参加する場合は、 vCenter Server がバージョン 6.7 Update 1 を実行していることを確認します。
* 既存の vSphere 6.5 環境に参加する場合は、 vCenter Server がバージョン 6.5 Update 2 以降を実行していることを確認します。
* 既存の vSphere 環境のネットワークの詳細と管理者クレデンシャルを取得します。


.タスクの内容
vCenter リンクモードを使用して接続されている複数の vCenter Server システムに参加した場合、 NetApp HCI は 1 つの vCenter Server システムのみを認識します。


NOTE: NetApp Element Plug-in for vCenter Serverを使用してを使用して他のvCenter Serverのクラスタリソースを管理することlink:https://docs.netapp.com/us-en/vcp/vcp_concept_linkedmode.html["vCenterリンクモード"^]は、ローカルストレージクラスタのみに制限されます。

.手順
. [Join and extend an existing vSphere deployment]*を選択します。
. ドメイン名または IP アドレスを「 * vCenter Server ドメイン名または IP アドレス * 」フィールドに入力します。ドメイン名を入力する場合は、表示される *DNS Server IP Address* フィールドにアクティブな DNS サーバの IP アドレスも入力する必要があります。
. vSphere 管理者のクレデンシャルを「 * User Name 」フィールドと「 Password * 」フィールドに入力します。
. 「 * Continue * 」を選択します。


[discrete]
== 詳細情報

* link:firmware_driver_versions.html["NetApp HCI でサポートされるファームウェアとESXiドライバのバージョン、NetApp HCI ストレージノードでサポートされるファームウェアのバージョンとファームウェアのバージョン"]

