---
sidebar: sidebar 
permalink: docs/task_mnode_api_get_authorizationtouse.html 
summary: REST API UI で管理サービス用の API を使用するには、事前に承認が必要です。 
keywords: netapp, hci, management node, mnode, api, token 
---
= REST API を使用するための許可を取得する
:allow-uri-read: 


[role="lead"]
REST API UI で管理サービス用の API を使用するには、事前に承認が必要です。アクセストークンを取得します。

トークンを取得するには、クラスタ管理者のクレデンシャルとクライアント ID を指定します。各トークンの有効期間は約 10 分です。トークンの期限が切れたら、再度承認して新しいアクセストークンを取得できます。

許可機能は管理ノードのインストールおよび導入時に設定します。トークンサービスは、セットアップ時に定義したストレージクラスタに基づいています。

.必要なもの
* クラスタで NetApp Element ソフトウェア 11.3 以降を実行している必要があります。
* バージョン 11.3 以降を実行する管理ノードを導入しておく必要があります。


.APIコマンド
[listing]
----
TOKEN=`curl -k -X POST https://MVIP/auth/connect/token -F client_id=mnode-client -F grant_type=password -F username=CLUSTER_ADMIN -F password=CLUSTER_PASSWORD|awk -F':' '{print $2}'|awk -F',' '{print $1}'|sed s/\"//g`
----
.REST API の UI の手順
. 管理ノードのIPアドレスとサービス名を入力して、サービスのREST API UIにアクセスします。次に例を示します。 `/mnode/`
+
[listing]
----
https://<ManagementNodeIP>/mnode/
----
. 「 * Authorize * （認証）」を選択
+

NOTE: または、任意のサービスAPIの横にあるロックアイコンを選択することもできます。

. 次の手順を実行します。
+
.. クラスタのユーザ名とパスワードを入力します。
.. クライアントIDにと入力し `mnode-client`ます。
.. クライアントシークレットの値は入力しないでください。
.. セッションを開始するには、 * Authorize * を選択します。


. [*Available Authorizations ( 使用可能な承認 )*] ダイアログボックスを閉じます。
+

NOTE: トークンの有効期限が切れたあとにコマンドを実行しようとすると `401 Error: UNAUTHORIZED`、メッセージが表示されます。このメッセージが表示された場合は、再度承認してください。



[discrete]
== 詳細情報

* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 向け NetApp Element プラグイン"^]

