---
sidebar: sidebar 
permalink: docs/task_hcc_expand_storage.html 
summary: NetApp HCI の導入が完了したら、ネットアップハイブリッドクラウド制御を使用して NetApp HCI のストレージリソースを拡張および設定できます。 
keywords: netapp, hci, on premise, expand, storage, cluster 
---
= NetApp HCI ストレージリソースを展開します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp HCI の導入が完了したら、ネットアップハイブリッドクラウド制御を使用して NetApp HCI のストレージリソースを拡張および設定できます。

.必要なもの
* 既存のノードと同じネットワークセグメントに未使用の空いている IPv4 アドレスがあることを確認してください（新しいノードは、同じタイプの既存のノードと同じネットワークにインストールする必要があります）。
* 次のいずれかのタイプの SolidFire ストレージクラスタアカウントがあることを確認しておきます。
+
** 初期導入時に作成されたネイティブの管理者アカウント
** Cluster Admin 、 Drives 、 Volumes 、 Nodes の各権限を持つカスタムユーザアカウント


* 新しいノードごとに次の操作を実行しておきます。
+
** の手順に従って、NetApp HCIシャーシに新しいノードを設置しlink:task_hci_installhw.html["インストール手順"]ます。
** 新しいノードのケーブルを配線して電源をオンにします


* 設置済みのストレージノードの管理 IPv4 アドレスを確認しておきます。IP アドレスは、 NetApp Element Plug-in for vCenter Server の * NetApp Element Management* > * Cluster * > * Nodes * タブで確認できます。
* 新しいノードのネットワークトポロジとケーブル配線が既存のストレージクラスタまたはコンピューティングクラスタと同じであることを確認しておきます。



TIP: ストレージリソースを拡張する際は、最大限の信頼性を実現するためにストレージ容量をすべてのシャーシに均等に分割してください。

.手順
. Webブラウザで管理ノードのIPアドレスを開きます。例：
+
[listing]
----
https://<ManagementNodeIP>
----
. NetApp HCI ストレージクラスタ管理者のクレデンシャルを指定して NetApp Hybrid Cloud Control にログインします。
. インターフェイスの右上隅にある*[Expand]*を選択します。
+
ブラウザに NetApp Deployment Engine が表示されます。

. ローカルのNetApp HCIストレージクラスタ管理者のクレデンシャルを指定してNetApp Deployment Engineにログインします。
+

NOTE: Lightweight Directory Access Protocolのクレデンシャルを使用してログインすることはできません。

. [ようこそ]ページで、*[いいえ]*を選択し、*[続行]*を選択します。
. [使用可能なインベントリ]*ページで、追加するストレージノードを選択し、*[続行]*を選択します。
. [* ネットワークの設定 * ] ページで、初期導入時に一部のネットワーク情報が検出されました。シリアル番号順に表示された新しいストレージノードのそれぞれについて、新しいネットワーク情報を割り当てる必要があります。新しいストレージノードごとに、次の手順を実行します。
+
.. * ホスト名 *: NetApp HCI が名前のプレフィックスを検出した場合は、 [ 検出された名前のプレフィックス ] フィールドから名前のプレフィックスをコピーし、 [ ホスト名 ] フィールドに追加した新しい一意のホスト名のプレフィックスとして挿入します。
.. * 管理アドレス * ：管理ネットワークサブネットにある新しいストレージノードの管理 IP アドレスを入力します。
.. * ストレージ（ iSCSI ） IP アドレス * ： iSCSI ネットワークサブネット内にある新しいストレージノードの iSCSI IP アドレスを入力します。
.. 「 * Continue * 」を選択します。
+

NOTE: 入力した IP アドレスの検証には時間がかかることがあります。 NetApp HCIIP アドレス検証が完了すると、 Continue （続行）ボタンが使用可能になります。



. [ ネットワーク設定 ] セクションの [ * レビュー ] ページでは、新しいノードが太字で表示されます。セクションを変更するには、次の手順を実行します。
+
.. そのセクションの * 編集 * を選択します。
.. 完了したら、以降のすべてのページで* Continue *を選択して、[Review]ページに戻ります。


. * オプション * ：ネットアップがホストする Active IQ サーバにクラスタの統計情報とサポート情報を送信しない場合は、最後のチェックボックスをオフにします。
+
これにより、 NetApp HCI のリアルタイムの健常性診断の監視機能が無効になります。この機能を無効にすると、ネットアップによる NetApp HCI のプロアクティブなサポートと監視が行われなくなるため、本番環境が影響を受ける前に問題を検出して解決できなくなります。

. [ * ノードの追加 * ] を選択します。
+
リソースの追加と設定の進捗状況は、 NetApp HCI で監視できます。

. * オプション * ：新しいストレージノードが Element Plug-in for vCenter Server に表示されることを確認します。
+

NOTE: 2 ノードストレージクラスタを 4 ノード以上に拡張した場合でも、ストレージクラスタで以前に使用されていた監視ノードのペアは、 vSphere ではスタンバイ仮想マシンとして表示されます。新しく拡張したストレージクラスタでは使用されません。VMリソースを再利用する場合は、監視ノードの仮想マシンを使用できます。link:task_hci_removewn.html["手動で削除します"]



[discrete]
== 詳細情報

* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 向け NetApp Element プラグイン"^]

