---
sidebar: sidebar 
permalink: docs/task_nde_configure_credentials.html 
summary: NetApp HCI の導入時に VMware vSphere を設定する方法について説明します。 
keywords: netapp, hci, netapp deployment engine, deployment, vsphere 
---
= NetApp HCI クレデンシャルを設定する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
導入時に、新しく導入する VMware vSphere 環境、 NetApp HCI のコンピューティングリソースとストレージリソース、および管理ノードで使用する一連のクレデンシャルを定義します。既存の vSphere 環境に NetApp HCI を導入する場合、既存の vCenter Server にこれらのクレデンシャルは適用されません。

.タスクの内容
NetApp HCI Deployment Engine で設定するクレデンシャルについては、次の点に注意してください。

* * NetApp Hybrid Cloud Control （ HCC ）または Element UI * ：導入の成功時に NetApp HCC または Element ユーザインターフェイスにログインするには、この導入手順で指定したユーザ名とパスワードを使用します。
* * VMware vCenter *：vCenterにログインするには（導入環境の一部としてインストールされている場合）、ユーザ名にサフィックスまたはビルトイン `Administrator@vsphere.local`ユーザアカウントを使用し、この導入手順で指定したパスワードを使用します `@vsphere.local`。
* * VMware ESXi *：コンピューティングノードのESXiにログインするには、この導入手順で指定したユーザ名とパスワードを使用し `root`ます。


VMware vCenter インスタンスと連携するために、 NetApp Hybrid Cloud Control では次のいずれかを使用します。

* 導入時にインストールされたvCenterインスタンス上の組み込みの `Administrator@vsphere.local`ユーザアカウント。
* 既存の VMware vCenter Server への NetApp HCI 環境の接続に使用した vCenter クレデンシャル。


.手順
. [*Credentials] ページで、 [*User Name*] フィールドにユーザ名を入力します。
. [* パスワード * ] フィールドにパスワードを入力します。パスワードは、「 * Password must contain * 」ボックスに表示されるパスワード基準に準拠している必要があります。
. パスワードの再入力 * フィールドにパスワードを確認します。
. 「 * Continue * 」を選択します。


[discrete]
== 詳細情報

* link:firmware_driver_versions.html["NetApp HCI でサポートされるファームウェアとESXiドライバのバージョン、NetApp HCI ストレージノードでサポートされるファームウェアのバージョンとファームウェアのバージョン"]
* vCenterおよびESXiクレデンシャルをあとで更新するには、を参照してくださいlink:task_hci_credentials_vcenter_esxi.html["vCenter または ESXi のクレデンシャルを更新します"]。

