---
sidebar: sidebar 
permalink: docs/task_nde_hci_power_off_storage.html 
summary: NetApp HCI コンピューティングノードの電源をオフにする方法について説明します。 
keywords: netapp, hci, netapp deployment engine, deployment, vsphere 
---
= NetApp HCI システムのストレージリソースの電源をオフにします
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp HCIのストレージリソースの電源をオフにするときは、Element APIメソッドを使用してストレージノードを適切に停止する必要 `Shutdown`があります。

.手順
コンピューティングリソースの電源をオフにしたら、 Web ブラウザを使用して、 NetApp HCI ストレージクラスタのすべてのノードをシャットダウンします。

. ストレージクラスタにログインし、正しい MVIP に接続していることを確認します。
. （オプション）ホストからのすべてのI/O処理が停止したことを確認します。
+
.. 使用している1つ以上のハイパーバイザーに適したコマンドを使用して、ホスト側からのI/Oを休止します。
.. クラスタUIで、* Reporting *>* Overview *を選択します。[クラスタの入出力]グラフにアクティビティが表示されていないことを確認します。
.. すべてのI/O処理が停止したら、20分待ってからクラスタをシャットダウンします。


. iSCSI セッション数が 0 であることを確認します。
. クラスタ > ノード > アクティブ * と進み、クラスタ内のすべてのアクティブノードのノード ID を記録します。
. NetApp HCIストレージクラスタの電源をオフにするには、Webブラウザを開き、次のURLを使用して電源オフおよび停止の手順を実行します。はNetApp HCIストレージシステムの管理IPアドレスで、 `nodes=[]`アレイには手順4で記録したノードIDが含まれています `{MVIP}`。例：
+
[listing]
----
https://{MVIP}/json-rpc/1.0?method=Shutdown&nodes=[1,2,3,4]&option=halt
----
+

NOTE: シークレットウィンドウでコマンドを実行すると、保存されているURLから以降の段階でコマンドが実行されないようにすることができます。

. クラスタ管理者のユーザ名とパスワードを入力します。
. すべてのストレージクラスタノードがAPI結果のセクションに含まれていることを確認して、API呼び出しが正常に返されたことを確認します `successful`。
+
すべての NetApp HCI ストレージノードの電源がオフになりました。

. [戻る]ボタンを選択しないようにブラウザまたはタブを閉じてAPI呼び出しを繰り返します。


[NOTE]
====
クラスタを再起動するときは、特定の手順に従ってすべてのノードがオンラインになったことを確認する必要があります。

. 重大度の重大度とクラスタの障害がすべて解決されたことを確認します `volumesOffline`。
. クラスタが安定するまで10～15分待ちます。
. データにアクセスするためのホストの起動を開始します。


メンテナンス後にノードの電源をオンにして正常であることを確認する時間を長くしたい場合は、データの同期を遅らせて不要なビンの同期を回避する方法についてテクニカルサポートにお問い合わせください。

====


== 詳細情報

* link:firmware_driver_versions.html["NetApp HCI でサポートされるファームウェアとESXiドライバのバージョン、NetApp HCI ストレージノードでサポートされるファームウェアのバージョンとファームウェアのバージョン"]

