---
sidebar: sidebar 
permalink: docs/task_mnode_enable_alerts.html 
summary: NetApp HCI システムでアラートを監視するように設定を行うことができます。 
keywords: netapp, element, management node, mnode, ui, alerts, alert monitoring 
---
= NetApp HCI でアラート監視を設定する
:allow-uri-read: 


[role="lead"]
NetApp HCI システムでアラートを監視するように設定を行うことができます。

NetApp HCI のアラート監視は、 NetApp HCI ストレージクラスタのシステムアラートを vCenter Server に転送して、 vSphere Web Client インターフェイスで NetApp HCI のすべてのアラートを表示できるようにします。

. ノード管理ノードUIを開き(`https://[IP address]:442`ます）。
. [Alert Monitor]タブを選択します。
. アラート監視オプションを設定します。




== アラート監視オプション

[cols="2*"]
|===
| オプション | 製品説明 


| Alert Monitor テストを実行します  a| 
モニタシステムテストを実行して次の項目を確認します。

* NetApp HCI と VMware vCenter の接続
* データストア情報を使用した NetApp HCI と VMware vCenter のペアリング QoSSIOC サービスによって提供されます
* 現在の NetApp HCI アラームと vCenter アラームのリスト




| アラートを収集します | NetApp HCI ストレージアラームの vCenter への転送を有効または無効にします。ドロップダウンリストからターゲットのストレージクラスタを選択できます。このオプションのデフォルト設定はです `Enabled`。 


| ベストプラクティスアラートを収集 | NetApp HCI ストレージのベストプラクティスアラートの vCenter への転送を有効または無効にします。ベストプラクティスアラートは、最適化されていないシステム構成によってトリガーされた障害です。このオプションのデフォルト設定はです `Disabled`。無効にすると、 NetApp HCI ストレージのベストプラクティスアラートは vCenter に表示されません。 


| サポートデータをAIQに送信  a| 
VMware vCenter から NetApp SolidFire Active IQ へのサポートデータと監視データのフローを制御します。

オプションは次のとおりです。

* Enabled ： vCenter アラーム、 NetApp HCI ストレージアラーム、およびサポートデータがすべて NetApp SolidFire Active IQ に送信されます。これにより、NetAppはNetApp HCIのインストールをプロアクティブにサポートおよび監視できるため、システムに影響を与える前に潜在的な問題を検出して解決できます。
* Disabled ： vCenter アラーム、 NetApp HCI ストレージアラーム、サポートデータはいずれも NetApp SolidFire Active IQ に送信されません。



NOTE: NetApp Deployment Engineを使用して*[Send data to AIQ *]オプションをオフにした場合は、このページから管理ノードのREST APIを使用してサービスを設定する必要がlink:task_mnode_enable_activeIQ.html["テレメータを有効にします"]あります。



| コンピューティングノードのデータを AIQ に送信  a| 
コンピューティングノードから NetApp SolidFire Active IQ へのサポートデータと監視データのフローを制御します。

オプションは次のとおりです。

* Enabled ：コンピューティングノードに関するサポートデータと監視データが NetApp SolidFire Active IQ に転送されるため、コンピューティングノードのハードウェアをプロアクティブにサポートできます。
* Disabled ：コンピューティングノードに関するサポートデータと監視データは NetApp SolidFire Active IQ に転送されません。



NOTE: NetApp Deployment Engineを使用して*[Send data to AIQ *]オプションをオフにした場合は、このページから管理ノードのREST APIを使用してサービスを設定する必要がlink:task_mnode_enable_activeIQ.html["テレメータを有効にします"]あります。

|===
[discrete]
== 詳細はこちら

* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 向け NetApp Element プラグイン"^]
* https://www.netapp.com/hybrid-cloud/hci-documentation/["NetApp HCI のリソースページ"^]

