---
sidebar: sidebar 
permalink: docs/task_hcc_upgrade_storage_firmware.html 
summary: NetApp HCI システムのアップグレードの一環として、ストレージノードに関連付けられているファームウェアをアップグレードします。 
keywords: netapp, element, hcc, firmware, storage firmware 
---
= ストレージファームウェアをアップグレードします
:allow-uri-read: 


[role="lead"]
Element 12.0 以降および管理サービスバージョン 2.14 以降では、 NetApp Hybrid Cloud Control の UI と REST API を使用して、 H シリーズストレージノードでファームウェアのみのアップグレードを実行できます。この手順では、 Element ソフトウェアはアップグレードされず、 Element のメジャーリリース以外のバージョンのストレージファームウェアもアップグレードできます。

.必要なもの
* * admin 権限 * ：アップグレードを実行する権限がストレージクラスタ管理者に付与されています。
* * システム時間の同期 * ：すべてのノードのシステム時間が同期されており、 NTP がストレージクラスタとノードに対して正しく設定されていることを確認しておきます。各ノードで、ノードWeb UIでDNSネームサーバを設定する必要があり(`https://[IP address]:442`ます）。時刻のずれに関連する未解決のクラスタ障害が発生していないことを確認します。
* * システムポート * ： NetApp Hybrid Cloud Control をアップグレードに使用している場合は、必要なポートが開いていることを確認しておきます。詳細については、を参照してください link:hci_prereqs_required_network_ports.html["ネットワークポート"] 。
* * 管理ノード * ： NetApp Hybrid Cloud Control の UI および API では、環境内の管理ノードはバージョン 11.3 を実行しています。
* * 管理サービス * ：管理サービスバンドルを最新バージョンに更新しました。



IMPORTANT: Element ソフトウェアバージョン 12.0 を実行している H610S ストレージノードについては、ストレージファームウェアバンドル 2.27 にアップグレードする前に「 D パッチ」「 St-909 」を適用する必要があります。アップグレード前に、ネットアップサポートに問い合わせて D パッチを入手します。を参照して link:rn_storage_firmware_2.27.html["Storage Firmware Bundle 2.27 Release Notes"]


IMPORTANT: ストレージノードのファームウェアをアップグレードする前に、最新の管理サービスバンドルにアップグレードする必要があります。Elementソフトウェアをバージョン12.2に更新する場合は、管理サービス2.14.60以降が必要です。

* * クラスタの健全性 * ：健全性チェックを実行しました。を参照して link:task_hcc_upgrade_element_prechecks.html["ストレージをアップグレードする前に、 Element ストレージの健全性チェックを実行します"]
* * H610S ノードの BMC を更新 * ： H610S ノードの BMC バージョンをアップグレードしました。を参照して link:rn_H610S_BMC_3.84.07.html["リリースノートおよびアップグレード手順"]



NOTE: ハードウェアのファームウェアとドライバファームウェアの完全なマトリックスについては、を参照してくださいlink:firmware_driver_versions.html["NetApp HCI ストレージノードでサポートされるファームウェアのバージョン"]。

* *エンドユーザライセンス契約（EULA）*：管理サービス2.20.69以降では、NetApp Hybrid Cloud Control UIまたはAPIを使用してストレージファームウェアをアップグレードする前に、EULAに同意して保存する必要があります。
+
.. Webブラウザで管理ノードのIPアドレスを開きます。
+
[listing]
----
https://<ManagementNodeIP>
----
.. ストレージクラスタ管理者のクレデンシャルを指定して NetApp Hybrid Cloud Control にログインします。
.. インターフェイスの右上にある [* Upgrade] を選択します。
.. EULAがポップアップ表示されます。下にスクロールして、[現在および今後のすべての更新を許可する*]を選択し、[保存*]を選択します。




.アップグレードオプション
次のいずれかのストレージファームウェアアップグレードオプションを選択します。

* <<NetApp Hybrid Cloud Control UI を使用してストレージファームウェアをアップグレードします>>
* <<NetApp Hybrid Cloud Control API を使用してストレージファームウェアをアップグレードします>>




== NetApp Hybrid Cloud Control UI を使用してストレージファームウェアをアップグレードします

NetApp Hybrid Cloud Control の UI を使用して、クラスタ内のストレージノードのファームウェアをアップグレードできます。

.必要なもの
* 管理ノードがインターネットに接続されていない場合は、を使用しています https://mysupport.netapp.com/site/products/all/details/element-software/downloads-tab/download/62654/Storage_Firmware_Bundle["ストレージファームウェアのバンドルをダウンロードします"^]。



CAUTION: NetApp Hybrid Cloud Controlを使用してストレージクラスタをアップグレードする際の潜在的な問題とその対処方法については、を参照してください https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/NetApp_HCI/Potential_issues_and_workarounds_when_running_storage_upgrades_using_NetApp_Hybrid_Cloud_Control["技術情報"^]。


TIP: アップグレードプロセスにはノードあたり約 30 分かかります。

.手順
. Webブラウザで管理ノードのIPアドレスを開きます。
+
[listing]
----
https://<ManagementNodeIP>
----
. ストレージクラスタ管理者のクレデンシャルを指定して NetApp Hybrid Cloud Control にログインします。
. インターフェイスの右上にある [* Upgrade] を選択します。
. [* Upgrades] ページで、 [* Storage] を選択します。
+
[NOTE]
====
[* ストレージ * ] タブには、インストールの一部であるストレージクラスタが一覧表示されます。NetApp Hybrid Cloud Control からクラスタにアクセスできない場合は、 * Upgrades * ページに表示されません。Element 12.0 以降を実行しているクラスタでは、これらのクラスタの現在のファームウェアバンドルバージョンが表示されます。1 つのクラスタ内のノードでファームウェアバージョンが異なる場合やアップグレードが進むにつれて、「 * Current Firmware Bundle Version * 」列に「 * Multiple * 」と表示されます。「 * multiple * 」を選択すると、「 * Nodes * 」ページに移動してファームウェアバージョンを比較できます。すべてのクラスタで 12.0 よりも前のバージョンの Element を実行している場合、ファームウェアバンドルのバージョン番号に関する情報は表示されません。この情報は、 * Nodes * ページでも確認できます。を参照して link:task_hcc_nodes.html["インベントリを表示します"]

クラスタが最新の状態であり、アップグレードパッケージがない場合は、「 * Element * 」タブと「 * Firmware only * 」タブは表示されません。これらのタブは、アップグレードの実行中は表示されません。[ * 要素 * ] タブが表示されているが、 [ * ファームウェアのみ * ] タブが表示されていない場合は、ファームウェアパッケージは利用できません。

====
. アップグレードするクラスタの横にあるドロップダウン矢印を選択します。
. [* Browse] を選択して、ダウンロードしたアップグレード・パッケージをアップロードします。
. アップロードが完了するまで待ちます。進捗バーにアップロードのステータスが表示されます。
+

CAUTION: ブラウザウィンドウから別の場所に移動すると、ファイルのアップロードが失われます。

+
ファイルのアップロードと検証が完了すると、画面にメッセージが表示されます。検証には数分かかることがあります。この段階でブラウザウィンドウから移動しても、ファイルのアップロードは維持されます。

. 「 * ファームウェアのみ * 」を選択し、利用可能なアップグレードバージョンから選択します。
. [* アップグレードの開始 * ] を選択します。
+

TIP: アップグレード中は、アップグレードステータス * が変更され、プロセスのステータスが反映されます。また、アップグレードの一時停止など、実行する操作に応じて変更が加えられたか、またはアップグレードでエラーが返された場合も変更されます。を参照して <<アップグレードステータスが変わります>>

+

NOTE: アップグレードの実行中は、ページを離れてあとから表示し、進捗状況の監視を続行できます。クラスタの行が折りたたまれている場合、ページではステータスと現在のバージョンは動的に更新されません。表を更新するには、クラスタの行を展開する必要があります。また、ページを更新することもできます。



アップグレードの完了後にログをダウンロードできます。



=== アップグレードステータスが変わります

アップグレードプロセスの実行前、実行中、実行後に、 UI の * アップグレードステータス * 列に表示されるさまざまな状態を以下に示します。

[cols="2*"]
|===
| アップグレードの状態 | 製品説明 


| 最新 | クラスタが最新の Element バージョンにアップグレードされたか、ファームウェアが最新バージョンにアップグレードされました。 


| 検出できません | このステータスは、ストレージサービスAPIがアップグレードステータスの一覧に含まれていないアップグレードステータスを返した場合に表示されます。 


| 使用可能なバージョン | Element / ストレージファームウェアの新しいバージョンをアップグレードできます。 


| 実行中 | アップグレードを実行中です。進行状況バーにアップグレードステータスが表示されます。画面にはノードレベルの障害も表示され、アップグレードの進行に伴いクラスタ内の各ノードのノード ID も表示されます。各ノードのステータスは、 Element UI または NetApp Element Plug-in for vCenter Server UI を使用して監視できます。 


| アップグレードを一時停止中 | アップグレードを一時停止することもできます。アップグレードプロセスの状態によっては、一時停止処理が成功するか失敗するかが決まります。一時停止処理の確認を求める UI プロンプトが表示されます。アップグレードを一時停止する前にクラスタが安全な場所にあることを確認するには、アップグレード処理が完全に一時停止されるまでに最大 2 時間かかることがあります。アップグレードを再開するには、 * Resume * （続行）を選択します。 


| 一時停止 | アップグレードを一時停止した。[* Resume （続行） ] を選択して、プロセスを再開します。 


| エラー | アップグレード中にエラーが発生しました。エラーログをダウンロードして、ネットアップサポートに送信できます。エラーを解決したら、ページに戻って * Resume * （続行）を選択します。アップグレードを再開すると、システムが健全性チェックを実行してアップグレードの現在の状態を確認している間、進捗状況バーが数分間後方に移動します。 
|===


== NetApp Hybrid Cloud を使用してアップグレードに失敗した場合の動作 制御

アップグレード中にドライブまたはノードで障害が発生した場合は、 Element UI にクラスタエラーが表示されます。アップグレードプロセスは次のノードに進まず、クラスタの障害が解決するまで待機します。UI の進捗状況バーには、アップグレードがクラスタの障害の解決を待機していることが表示されます。アップグレードはクラスタが正常に完了するまで待機するため、この段階で UI で * Pause * を選択することはできません。障害の調査に役立てるには、ネットアップサポートに問い合わせる必要があります。

NetApp Hybrid Cloud Control には 3 時間の待機時間があらかじめ設定されています。この時間内に、次のいずれかの状況が発生する可能性があります。

* クラスタの障害は 3 時間以内に解決され、アップグレードが再開されます。このシナリオでは対処は必要ありません。
* 問題は 3 時間後も解消されず、アップグレードのステータスが「 Error 」（エラー）と赤のバナーを表示します。問題が解決したら、「 * Resume 」（続行）を選択してアップグレードを再開できます。
* 3 時間以内に対処するために、アップグレードを一時的に中止する必要があることがネットアップサポートによって確認されました。サポートは API を使用してアップグレードを中止します。



CAUTION: ノードの更新中にクラスタのアップグレードを中止すると、そのノードからドライブが強制的に削除されることがあります。ドライブが強制的に削除された場合、ネットアップサポートに依頼して手動でドライブを元に戻す処理がアップグレード時に必要になります。ノードでファームウェアの更新や更新後の同期処理に時間がかかる可能性があります。アップグレードが停止していると思われる場合は、ネットアップサポートにお問い合わせください。



== NetApp Hybrid Cloud Control API を使用してストレージファームウェアをアップグレードします

API を使用して、クラスタ内のストレージノードを最新バージョンの Element ソフトウェアにアップグレードできます。API の実行には、任意の自動化ツールを使用できます。ここで説明する API ワークフローでは、例として管理ノードで使用可能な REST API UI を使用します。

.手順
. 管理ノードからアクセス可能なデバイスに最新のストレージファームウェアアップグレードパッケージをダウンロードします。にアクセスし、 https://mysupport.netapp.com/site/products/all/details/element-software/downloads-tab/download/62654/Storage_Firmware_Bundle["Element ソフトウェアストレージファームウェアのバンドルページ"^]最新のストレージファームウェアイメージをダウンロードします。
. ストレージファームウェアのアップグレードパッケージを管理ノードにアップロードします。
+
.. 管理ノードで管理ノード REST API UI を開きます。
+
[listing]
----
https://<ManagementNodeIP>/package-repository/1/
----
.. 「 * Authorize * 」（認証）を選択して、次の手順を実行
+
... クラスタのユーザ名とパスワードを入力します。
... クライアントIDにと入力し `mnode-client`ます。
... セッションを開始するには、 * Authorize * を選択します。
... 承認ウィンドウを閉じます。


.. REST API UI から * POST/packages * を選択します。
.. [* 試してみてください * ] を選択します。
.. [* Browse] を選択して、アップグレード・パッケージを選択します。
.. 「 * Execute * 」を選択してアップロードを開始します。
.. 応答から、(`"id"`後の手順で使用するためにパッケージIDをコピーして保存します。


. アップロードのステータスを確認します。
+
.. REST API UI から、 * GEGET 処理対象 / パッケージ間の一時的なグループ / ｛ id ｝ 一時的なグループ / ステータス * を選択します。
.. [* 試してみてください * ] を選択します。
.. 前の手順でコピーしたファームウェアパッケージ ID を * id * で入力します。
.. ステータス要求を開始するには、 * Execute * を選択します。
+
完了すると、応答にと `SUCCESS`表示され `state`ます。



. インストールアセット ID を確認します。
+
.. 管理ノードで管理ノード REST API UI を開きます。
+
[listing]
----
https://<ManagementNodeIP>/inventory/1/
----
.. 「 * Authorize * 」（認証）を選択して、次の手順を実行
+
... クラスタのユーザ名とパスワードを入力します。
... クライアントIDにと入力し `mnode-client`ます。
... セッションを開始するには、 * Authorize * を選択します。
... 承認ウィンドウを閉じます。


.. REST API UI から、 * GET / Installations * を選択します。
.. [* 試してみてください * ] を選択します。
.. [* Execute] を選択します。
.. 応答から、インストールアセットID(`id`をコピーします）。
+
[listing, subs="+quotes"]
----
*"id": "abcd01e2-xx00-4ccf-11ee-11f111xx9a0b",*
"management": {
  "errors": [],
  "inventory": {
    "authoritativeClusterMvip": "10.111.111.111",
    "bundleVersion": "2.14.19",
    "managementIp": "10.111.111.111",
    "version": "1.4.12"
----
.. REST API UI から、 * GET / Installations / ｛ id ｝ * を選択します。
.. [* 試してみてください * ] を選択します。
.. インストールアセット ID を *id* フィールドに貼り付けます。
.. [* Execute] を選択します。
.. この応答で、(`"id"`以降の手順で使用するためにアップグレードするクラスタのストレージクラスタIDをコピーして保存します。
+
[listing, subs="+quotes"]
----
"storage": {
  "errors": [],
  "inventory": {
    "clusters": [
      {
        "clusterUuid": "a1bd1111-4f1e-46zz-ab6f-0a1111b1111x",
        *"id": "a1bd1111-4f1e-46zz-ab6f-a1a1a111b012",*
----


. ストレージファームウェアのアップグレードを実行します。
+
.. 管理ノードでストレージ REST API UI を開きます。
+
[listing]
----
https://<ManagementNodeIP>/storage/1/
----
.. 「 * Authorize * 」（認証）を選択して、次の手順を実行
+
... クラスタのユーザ名とパスワードを入力します。
... クライアントIDにと入力し `mnode-client`ます。
... セッションを開始するには、 * Authorize * を選択します。
... ウィンドウを閉じます。


.. [*POST/upgrade*] を選択します。
.. [* 試してみてください * ] を選択します。
.. パラメータフィールドにアップグレードパッケージ ID を入力します。
.. パラメータフィールドにストレージクラスタ ID を入力します。
.. アップグレードを開始するには、 * Execute * を選択します。
+
応答の状態は次のとおり `initializing`です。

+
[listing, subs="+quotes"]
----
{
  "_links": {
    "collection": "https://localhost:442/storage/upgrades",
    "self": "https://localhost:442/storage/upgrades/3fa85f64-1111-4562-b3fc-2c963f66abc1",
    "log": https://localhost:442/storage/upgrades/3fa85f64-1111-4562-b3fc-2c963f66abc1/log
  },
  "storageId": "114f14a4-1a1a-11e9-9088-6c0b84e200b4",
  "upgradeId": "334f14a4-1a1a-11e9-1055-6c0b84e2001b4",
  "packageId": "774f14a4-1a1a-11e9-8888-6c0b84e200b4",
  "config": {},
  *"state": "initializing",*
  "status": {
    "availableActions": [
      "string"
    ],
    "message": "string",
    "nodeDetails": [
      {
        "message": "string",
        "step": "NodePreStart",
        "nodeID": 0,
        "numAttempt": 0
      }
    ],
    "percent": 0,
    "step": "ClusterPreStart",
    "timestamp": "2020-04-21T22:10:57.057Z",
    "failedHealthChecks": [
      {
        "checkID": 0,
        "name": "string",
        "displayName": "string",
        "passed": true,
        "kb": "string",
        "description": "string",
        "remedy": "string",
        "severity": "string",
        "data": {},
        "nodeID": 0
      }
    ]
  },
  "taskId": "123f14a4-1a1a-11e9-7777-6c0b84e123b2",
  "dateCompleted": "2020-04-21T22:10:57.057Z",
  "dateCreated": "2020-04-21T22:10:57.057Z"
}
----
.. (`"upgradeId"`応答の一部であるアップグレードIDをコピーします。


. アップグレードの進捗状況と結果を確認します。
+
.. Get Sebring/upgrades/｛ upgradeId ｝ * を選択します。
.. [* 試してみてください * ] を選択します。
.. アップグレード ID は、前の手順のアップグレード ID として * upgradeId * と入力します。
.. [* Execute] を選択します。
.. アップグレード中に問題または特別な要件が発生した場合は、次のいずれかを実行します。
+
[cols="2*"]
|===
| オプション | 手順 


| 応答の本文にメッセージが含まれていることが原因で、クラスタの健常性に関する問題を修正する必要が `failedHealthChecks`あります。  a| 
... 各問題について記載されている特定の技術情報アーティクルに移動するか、指定された対処方法を実行します。
... KB を指定した場合は、関連する技術情報アーティクルに記載されているプロセスを完了します。
... クラスタの問題を解決したら、必要に応じて再認証し、 * PUT 処理の際に必要な数 / アップグレード / ｛ upgradeId ｝ * を選択します。
... [* 試してみてください * ] を選択します。
... アップグレード ID は、前の手順のアップグレード ID として * upgradeId * と入力します。
... 要求の本文にと入力し `"action":"resume"`ます。
+
[listing]
----
{
  "action": "resume"
}
----
... [* Execute] を選択します。




| メンテナンス時間が終了しているか別の理由で、アップグレードを一時停止する必要があります。  a| 
... 必要に応じて再認証し、 * PUT に成功 / アップグレード / ｛ upgradeId ｝ * を選択します。
... [* 試してみてください * ] を選択します。
... アップグレード ID は、前の手順のアップグレード ID として * upgradeId * と入力します。
... 要求の本文にと入力し `"action":"pause"`ます。
+
[listing]
----
{
  "action": "pause"
}
----
... [* Execute] を選択します。


|===
.. 必要に応じて、処理が完了するまで * Get Theple/upgrades/｛ upgradeId ｝ * API を複数回実行します。
+
アップグレード中、は `status`エラーが発生していないかどうかを示します `running`。各ノードをアップグレードすると、 `step`の値がに変わり `NodeFinished`ます。

+
の値がで `100`、が `state`になって `finished`いれば、アップグレードは正常に完了してい `percent`ます。





[discrete]
== 詳細情報

* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 向け NetApp Element プラグイン"^]
* https://www.netapp.com/hybrid-cloud/hci-documentation/["NetApp HCI のリソースページ"^]

