---
sidebar: sidebar 
permalink: docs/task_mnode_recover.html 
summary: NetApp Element ソフトウェアを実行しているクラスタの管理ノードをリカバリして再導入できます。設定によっては、管理ノード用に認証を再設定しなければならない場合があります。 
keywords: netapp, element, management node, mnode, disaster recovery, redeploy, VM 
---
= 管理ノードをリカバリ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
以前の管理ノードで永続ボリュームを使用していた場合は、 NetApp Element ソフトウェアを実行しているクラスタの管理ノードを手動でリカバリして再導入できます。

新しい OVA を導入して再導入スクリプトを実行すると、バージョン 11.3 以降を実行していた以前の管理ノードから設定データを取得することができます。

.必要なもの
* 以前の管理ノードでNetApp Elementソフトウェアバージョン11.3以降を実行しており、機能を使用していましたlink:concept_hci_volumes.html#persistent-volumes["永続ボリューム"]。
* 永続ボリュームを含むクラスタの MVIP と SVIP が必要です。
* クラスタバージョンで NetApp Element ソフトウェア 11.3 以降が実行されています。
* インストール環境では IPv4 を使用します。管理ノード 11.3 では IPv6 がサポートされません。
* NetApp Support Siteからソフトウェアをダウンロードする権限が必要です。
* 使用するプラットフォームに適した管理ノードイメージのタイプを特定しておきます。
+
[cols="30,30"]
|===
| プラットフォーム | インストールイメージのタイプ 


| Microsoft Hyper-V | .iso 


| KVM | .iso 


| VMware vSphere | .iso 、 .ova のいずれかです 


| Citrix XenServer | .iso 


| OpenStack | .iso 
|===


.手順
. <<ISO または OVA をダウンロードし、 VM を導入します>>
. <<ネットワークを設定します>>
. <<時刻同期を設定します>>
. <<管理ノードを設定>>




== ISO または OVA をダウンロードし、 VM を導入します

. NetAppサポートサイトのページから、インストールに対応したOVAまたはISOをダウンロードし https://mysupport.netapp.com/site/products/all/details/netapp-hci/downloads-tab["NetApp HCI"^]ます。
+
.. Download Latest Release * を選択し、 EULA に同意します。
.. ダウンロードする管理ノードのイメージを選択します。


. OVA をダウンロードした場合は、次の手順を実行します。
+
.. OVA を導入します。
.. ストレージクラスタが管理ノード（ eth0 ）とは別のサブネット上にある環境で永続ボリュームを使用する場合は、ストレージサブネット（ eth1 など）上の VM に 2 つ目のネットワークインターフェイスコントローラ（ NIC ）を追加するか、管理ネットワークからストレージネットワークへルーティング可能なことを確認します。


. ISO をダウンロードした場合は、次の手順を実行します。
+
.. 以下の構成でハイパーバイザーから新しい 64 ビットの仮想マシンを作成します。
+
*** 仮想 CPU × 6
*** 24GBのRAM
*** 400GB の仮想ディスク、シンプロビジョニング
*** インターネットアクセスとストレージ MVIP へのアクセスが可能な仮想ネットワークインターフェイス × 1
*** ストレージクラスタへの管理ネットワークアクセスが可能な仮想ネットワークインターフェイス×1。ストレージクラスタが管理ノード（ eth0 ）とは別のサブネット上にある環境で永続ボリュームを使用する場合は、ストレージサブネット（ eth1 ）上の VM に 2 つ目のネットワークインターフェイスコントローラ（ NIC ）を追加するか、管理ネットワークからストレージネットワークへルーティング可能なことを確認します。
+

IMPORTANT: このあとの手順で指示があるまでは、仮想マシンの電源をオンにしないでください。



.. 仮想マシンに ISO を接続し、 .iso インストールイメージでブートします。
+

NOTE: イメージを使用して管理ノードをインストールすると、スプラッシュ画面が表示されるまでに 30 秒程度かかることがあります。



. インストールが完了したら、管理ノードの仮想マシンの電源をオンにします。




== ネットワークを設定します

. ターミナルユーザインターフェイス（ TUI ）を使用して、管理ノードの管理ユーザを作成します。
+

TIP: メニューオプションを移動するには、上矢印キーまたは下矢印キーを押します。ボタン間を移動するには、 Tab キーを押します。ボタンからフィールドに移動するには、 Tab キーを押します。フィールド間を移動するには、上矢印キーまたは下矢印キーを押します。

. 管理ノードネットワーク（ eth0 ）を設定します。
+

NOTE: ストレージトラフィックを分離するために追加のNICが必要な場合は、別のNICの設定手順を参照してください。link:task_mnode_install_add_storage_NIC.html["ストレージネットワークインターフェイスコントローラ（ NIC ）の設定"]





== 時刻同期を設定します

. NTP を使用して管理ノードとストレージクラスタの間で時刻が同期されていることを確認します。



NOTE: Element 12..1 以降では、手順（ a ） ～ （ e ）が自動的に実行されます。管理ノード12.3.1の場合は、に進み、<<substep_f_recover_config_time_sync,サブステップ (f)>>時間の同期の設定を完了します。

. SSH またはハイパーバイザーが提供するコンソールを使用して、管理ノードにログインします。
. NTPDを停止します。
+
[listing]
----
sudo service ntpd stop
----
. NTP構成ファイルを編集し `/etc/ntp.conf`ます。
+
.. 各サーバの前に(`server 0.gentoo.pool.ntp.org`を追加して、デフォルトサーバをコメントアウトします `#`。
.. 追加するデフォルトのタイムサーバごとに新しい行を追加します。デフォルトのタイムサーバは、で使用するストレージクラスタで使用されているNTPサーバと同じである必要がありますlink:task_mnode_recover.html#configure-the-management-node["後の手順"]。
+
[listing]
----
vi /etc/ntp.conf

#server 0.gentoo.pool.ntp.org
#server 1.gentoo.pool.ntp.org
#server 2.gentoo.pool.ntp.org
#server 3.gentoo.pool.ntp.org
server <insert the hostname or IP address of the default time server>
----
.. 完了したら構成ファイルを保存します。


. 新しく追加したサーバと NTP 同期を強制します。
+
[listing]
----
sudo ntpd -gq
----
. NTPD を再起動します。
+
[listing]
----
sudo service ntpd start
----
. [[[[suf_recover_config_time_sync]] ハイパーバイザーを使用したホストとの時間同期を無効にします（ VMware の例を次に示します）。
+

NOTE: OpenStack 環境の .iso イメージなどで、 VMware 以外のハイパーバイザー環境に mNode を導入する場合は、同等のコマンドについてハイパーバイザーのドキュメントを参照してください。

+
.. 定期的な時刻同期を無効にします。
+
[listing]
----
vmware-toolbox-cmd timesync disable
----
.. サービスの現在のステータスを表示して確認します。
+
[listing]
----
vmware-toolbox-cmd timesync status
----
.. vSphereで、VMオプションのチェックボックスがオフになっていることを確認し `Synchronize guest time with host`ます。
+

NOTE: 今後 VM を変更する場合は、このオプションを有効にしないでください。






NOTE: 時刻の同期設定が完了したらNTPを編集しないでください。管理ノードでを実行するとNTPに影響するためです。<<step_6_recover_mnode_redeploy,再導入コマンド>>



== 管理ノードを設定

. 管理サービスバンドルの内容を保存する一時的なデスティネーションディレクトリを作成します。
+
[listing]
----
mkdir -p /sf/etc/mnode/mnode-archive
----
. 既存の管理ノードにインストールされていた管理サービスバンドル（バージョン2.15.28以降）をダウンロードし、ディレクトリに保存します `/sf/etc/mnode/`。
. 次のコマンドを使用して、ダウンロードしたバンドルを展開します。角かっこ内の値をバンドルファイル名に置き換えます。
+
[listing]
----
tar -C /sf/etc/mnode -xvf /sf/etc/mnode/[management services bundle file]
----
. 作成されたファイルをディレクトリに展開し `/sf/etc/mnode-archive`ます。
+
[listing]
----
tar -C /sf/etc/mnode/mnode-archive -xvf /sf/etc/mnode/services_deploy_bundle.tar.gz
----
. アカウントとボリュームの構成ファイルを作成します。
+
[listing]
----
echo '{"trident": true, "mvip": "[mvip IP address]", "account_name": "[persistent volume account name]"}' | sudo tee /sf/etc/mnode/mnode-archive/management-services-metadata.json
----
+
.. 次の各必須パラメータについて、 [] ブラケット（ブラケットを含む）の値を置き換えます。
+
*** *[mvip IP address]* ：ストレージクラスタの管理仮想 IP アドレス。で使用したストレージクラスタを使用して管理ノードを設定しlink:task_mnode_recover.html#configure-time-sync["NTP サーバの設定"]ます。
*** * [persistent volume account name] * ：このストレージクラスタ内のすべての永続ボリュームに関連付けられたアカウントの名前。




. クラスタでホストされている永続ボリュームに接続し、以前の管理ノードの設定データを使用してサービスを開始するには、管理ノードの再導入コマンドを設定して実行します。
+

NOTE: セキュアプロンプトにパスワードを入力するように求められます。クラスタがプロキシサーバの背後にある場合、パブリックネットワークに接続できるようにプロキシを設定する必要があります。

+
[listing]
----
sudo /sf/packages/mnode/redeploy-mnode --mnode_admin_user [username]
----
+
.. 角かっこ内の値を、管理ノードの管理者アカウントのユーザ名に置き換えます。一般には、管理ノードへのログインに使用したユーザアカウントのユーザ名です。
+

NOTE: ユーザ名を追加するか、または情報の入力を求めるプロンプトをスクリプトに表示することができます。

.. コマンドを実行します `redeploy-mnode`。再導入が完了すると、成功メッセージが表示されます。
.. システムのFully Qualified Domain Name（FQDN；完全修飾ドメイン名）を使用してElementまたはNetApp HCIのWebインターフェイス（管理ノードやNetApp Hybrid Cloud Controlなど）にアクセスする場合は、をlink:task_hcc_upgrade_management_node.html#reconfigure-authentication-using-the-management-node-rest-api["管理ノードの認証を再設定します"]参照してください。





IMPORTANT: 管理ノードで以前にSSH機能を無効にしていた場合は、リカバリした管理ノードでを実行する必要がありlink:task_mnode_ssh_management.html["SSH を再度無効にします"]ます。のSSH機能link:task_mnode_enable_remote_support_connections.html["ネットアップサポートの Remote Support Tunnel （ RST ）セッションアクセス"]は、管理ノードではデフォルトで有効になっています。

[discrete]
== 詳細はこちら

* link:concept_hci_volumes.html#persistent-volumes["永続ボリューム"]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 向け NetApp Element プラグイン"^]
* https://www.netapp.com/hybrid-cloud/hci-documentation/["NetApp HCI のリソースページ"^]

