---
sidebar: sidebar 
permalink: docs/task_hcc_edit_bmc_info.html 
summary: NetApp Hybrid Cloud Control を使用して、 NetApp HCI が接続できるようにベースボード管理コントローラ（ BMC ）の接続情報を編集できます。 
keywords: netapp, hci, BMC, connection, credentials, monitor 
---
= ベースボード管理コントローラの接続情報を編集します
:allow-uri-read: 


[role="lead"]
ベースボード管理コントローラ（ BMC ）の管理者クレデンシャルは、各コンピューティングノードの NetApp Hybrid Cloud Control で変更できます。BMCファームウェアをアップグレードする前や、NetApp Hybrid Cloud Controlに表示されるまたは `Unable to Detect`エラーを解決するために、クレデンシャルの変更が必要になる場合があり `Hardware ID not available`ます。

.必要なもの
BMC クレデンシャルを変更するためのクラスタ管理者の権限。


NOTE: ヘルスチェック時に BMC クレデンシャルを設定した場合、変更が * Nodes * ページに反映されるまでに最大 15 分かかることがあります。

.オプション
BMC クレデンシャルを変更するには、次のいずれかのオプションを選択します。

* <<NetApp Hybrid Cloud Control を使用して BMC の情報を編集します>>
* <<BMC の情報を編集するには、 REST API を使用します>>




== NetApp Hybrid Cloud Control を使用して BMC の情報を編集します

保存されている BMC クレデンシャルは、 NetApp Hybrid Cloud Control Dashboard を使用して編集できます。

.手順
. Webブラウザで管理ノードのIPアドレスを開きます。例：
+
[listing]
----
https://<ManagementNodeIP>
----
. NetApp HCI ストレージクラスタ管理者のクレデンシャルを指定して NetApp Hybrid Cloud Control にログインします。
. 左側のナビゲーション青いボックスで、 NetApp HCI のインストールを選択します。
+
NetApp Hybrid Cloud Control Dashboard が表示されます。

. 左側のナビゲーションで、 * ノード * を選択します。
. コンピューティングインベントリ情報を表示するには、*[Compute]*を選択します。
+
コンピューティングノードのリストが表示されます。「 * BMC Connection Status * 」列には、各コンピューティングノードでの BMC 接続試行の結果が表示されます。コンピューティングノードの接続試行が失敗した場合は、そのノードのエラーメッセージがこの列に表示されます。

. BMC接続エラーのあるコンピューティングノードに保存されているBMCクレデンシャルを追加または編集するには、エラーメッセージテキストで*[接続設定の編集]*を選択します。
. 表示されるダイアログで、このコンピューティングノードの BMC に対応する正しい管理者ユーザ名とパスワードを追加します。
. [ 保存（ Save ） ] を選択します。
. 保存されている BMC クレデンシャルが不足しているコンピューティングノードまたは正しくないコンピューティングノードに対して、手順 6~8 を繰り返します。



NOTE: BMC の情報を更新すると、インベントリが更新され、管理ノードのサービスで、アップグレードの完了に必要なすべてのハードウェアパラメータが認識されるようになります。



== BMC の情報を編集するには、 REST API を使用します

保存されている BMC クレデンシャルは、 NetApp Hybrid Cloud Control REST API を使用して編集できます。

.手順
. コンピューティングノードのハードウェアタグと BMC の情報を確認します。
+
.. 管理ノードでインベントリサービス REST API UI を開きます。
+
[listing]
----
https://<ManagementNodeIP>/inventory/1/
----
.. 「 * Authorize * 」（認証）を選択して、次の手順を実行
+
... クラスタのユーザ名とパスワードを入力します。
... クライアントIDにと入力し `mnode-client`ます。
... セッションを開始するには、 * Authorize * を選択します。
... 承認ウィンドウを閉じます。


.. REST API UI から、 * GET / Installations * を選択します。
.. [* 試してみてください * ] を選択します。
.. [* Execute] を選択します。
.. 応答から、インストールアセットID(`id`をコピーします）。
.. REST API UI から、 * GET / Installations / ｛ id ｝ * を選択します。
.. [* 試してみてください * ] を選択します。
.. インストールアセット ID を *id* フィールドに貼り付けます。
.. [* Execute] を選択します。
.. 応答から、ノードアセットID(`id`）、BMC IPアドレス(`chassisSerialNumber`）(`bmcAddress`、ノードシリアル番号をコピーして保存し、あとの手順で使用します。
+
[listing, subs="+quotes"]
----
"nodes": [
  {
    "bmcDetails": {
      *"bmcAddress": "10.117.1.111",*
      "credentialsAvailable": false,
      "credentialsValidated": false
    },
    *"chassisSerialNumber": "221111019323",*
    "chassisSlot": "C",
    "hardwareId": null,
    "hardwareTag": "00000000-0000-0000-0000-ac1f6ab4ecf6",
    *"id": "8cd91e3c-1b1e-1111-b00a-4c9c4900b000",*
----


. 管理ノードでハードウェアサービス REST API UI を開きます。
+
[listing]
----
https://<ManagementNodeIP>/hardware/2/
----
. 「 * Authorize * 」（認証）を選択して、次の手順を実行
+
.. クラスタのユーザ名とパスワードを入力します。
.. クライアントIDは、値がまだ入力されていない場合と同様に入力し `mnode-client`ます。
.. セッションを開始するには、 * Authorize * を選択します。
.. ウィンドウを閉じます。


. PUT /nodes/｛hardware_id｝*を選択します。
. [* 試してみてください * ] を選択します。
. 前の手順でパラメータに保存したノードアセットIDを入力し `hardware_id`ます。
. ペイロードに次の情報を入力します。
+
|===
| パラメータ | 製品説明 


| `assetId` | (`id`手順1（f）で保存したインストールアセットID）。 


| `bmcIp` | (`bmcAddress`手順1（k）で保存したBMC IPアドレス）。 


| `bmcPassword` | BMC にログインするための更新されたパスワード。 


| `bmcUsername` | BMC にログインするために更新されたユーザ名。 


| `serialNumber` | ハードウェアのシャーシのシリアル番号。 
|===
+
ペイロードの例：

+
[listing]
----
{
  "assetId": "7bb41e3c-2e9c-2151-b00a-8a9b49c0b0fe",
  "bmcIp": "10.117.1.111",
  "bmcPassword": "mypassword1",
  "bmcUsername": "admin1",
  "serialNumber": "221111019323"
}
----
. BMCクレデンシャルを更新するには、*[実行]*を選択します。成功すると、次のような応答が返されます。
+
[listing]
----
{
  "credentialid": "33333333-cccc-3333-cccc-333333333333",
  "host_name": "hci-host",
  "id": "8cd91e3c-1b1e-1111-b00a-4c9c4900b000",
  "ip": "1.1.1.1",
  "parent": "abcd01y3-ab30-1ccc-11ee-11f123zx7d1b",
  "type": "BMC"
}
----


[discrete]
== 詳細情報

* https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/NetApp_HCI/Known_issues_and_workarounds_for_Compute_Node_upgrades["コンピューティングノードのアップグレードに関する既知の問題と対処方法"^]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 向け NetApp Element プラグイン"^]

