---
sidebar: sidebar 
permalink: docs/task_upgrade_element_latest_healthtools.html 
summary: システムのアップグレードの一環として、最新の HealthTools for NetApp Element ソフトウェアにアップグレードする必要があります。 
keywords: netapp, HealthTools upgrade, sfupdate-healthtools, element 
---
= 最新の HealthTools にアップグレードします
:allow-uri-read: 


[role="lead"]
Element ストレージのアップグレードを開始する前に、 HealthTools スイートをアップグレードする必要があります。HealthTools のアップグレードは、実行している管理ノードと Element ソフトウェアが 11.1 以前の場合にのみ必要です。NetApp Hybrid Cloud Control を使用した Element のアップグレードには HealthTools は必要ありません。

.必要なもの
* 実行されている管理ノードは 11.0 、 11.1 、またはそれ以降です。
* 管理サービスをバージョン 2.1.326 以上にアップグレードしておきます。
+
NetApp Hybrid Cloud Control のアップグレードは、それよりも前のバージョンのサービスバンドルでは利用できません。

* 最新バージョンのをダウンロードし、インストールファイルを管理ノードにコピーしておき https://mysupport.netapp.com/site/products/all/details/element-healthtools/downloads-tab["HealthTools"^]ます。
+

TIP: ローカルにインストールされているHealthToolsのバージョンは、コマンドを実行して確認できます `sfupdate-healthtools -v`。

* ダークサイトで HealthTools を使用するには、次の追加手順を実行する必要があります。
+
** 管理ノードではないコンピュータにNetAppサポートサイトからをダウンロードしlink:https://library.netapp.com/ecm/ecm_get_file/ECMLP2840740["JSONファイル"^]、名前をに変更します。 `metadata.json`
** 管理ノードをダークサイトで起動して実行します。




.タスクの内容
HealthTools スイートのコマンドを実行するには権限を昇格する必要があります。コマンドの先頭にを `sudo`付けるか、ユーザをroot Privilegesにエスカレーションします。


NOTE: 使用する HealthTools のバージョンが、以下の入力例と応答よりも新しい場合があります。

.手順
. コマンドを実行し `sfupdate-healthtools <path to install file>`て、新しいHealthToolsソフトウェアをインストールします。
+
入力例：

+
[listing]
----
sfupdate-healthtools /tmp/solidfire-healthtools-2020.03.01.09.tgz
----
+
回答例：

+
[listing]
----
Checking key signature for file /tmp/solidfirehealthtools-2020.03.01.09/components.tgz
installing command sfupdate-healthtools
Restarting on version 2020.03.01.09
sfupdate-healthtools /sf/bin/sfupdate-healthtools -r 2020.03.01.09
installing command sfupgradecheck
installing command sfinstall
installing command sfresetupgrade
----
. コマンドを実行し `sfupdate-healthtools -v`て、インストールされているバージョンがアップグレードされたことを確認します。
+
回答例：

+
[listing]
----
Currently installed version of HealthTools:
2020.03.01.09
----


[discrete]
== 詳細情報

* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 向け NetApp Element プラグイン"^]

