---
sidebar: sidebar 
permalink: docs/task_nde_configure_net_settings.html 
summary: NetApp HCI 導入ネットワークの設定方法について説明します。 
keywords: netapp, hci, deployment, compatibility, nodes 
---
= ネットワークの設定
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp HCI には、ネットワーク設定ページが用意されており、ネットワーク設定を簡単に行うことができます。簡易フォームに入力すると、ネットワーク設定ページの残りの情報の多くが NetApp HCI によって自動的に入力されます。その後、最終的なネットワーク設定を入力し、ネットワーク設定が正しいことを確認してから次に進んでください。フォームの項目はすべて入力する必要はありません。

.必要なもの
* 次の情報を入手しておきます。
+
** ホストとストレージクラスタの命名に使用するプレフィックス
** 管理ネットワーク、 iSCSI ネットワーク、および vMotion ネットワークで使用するサブネットマスク、開始 IP アドレス、デフォルトゲートウェイ、および VLAN ID
** 導入する VMware vCenter 環境の IP アドレス、デフォルトゲートウェイ、 VLAN ID 、およびサブネットマスク
** NetApp HCI のネットワークタイムプロトコル（ NTP ）サーバアドレス
** NetApp HCI の DNS サーバの IP アドレス情報


* vSphere Distributed Switch を導入する場合は、導入完了後に適用する vSphere Enterprise Plus ライセンスを準備しておきます。
* ターミナルユーザインターフェイス（ TUI ）設定時にノードポートに VLAN ID を割り当てた場合は、ネットワーク設定時に同じ VLAN ID でそれらのポートを設定する必要があります。接続されたスイッチポートで、タグ付きホストポートをアクセスポートまたはネイティブ VLAN として設定する必要はありません。
* ネットワークスイッチの構成が正しいことを確認しておきます。スイッチの設定（ VLAN や MTU サイズなど）に誤りがあると、導入エラーが発生する可能性があります。


.タスクの内容
コンピューティングノードにケーブル 2 本のネットワークトポロジを使用する場合は、導入するすべてのコンピューティングノードおよびストレージノードの vMotion ネットワークとストレージネットワークに VLAN ID を使用する必要があります（管理ネットワークの VLAN ID は任意です）。


NOTE: 導入前にホスト側で VLAN タギングが必要な環境で、 NetApp Deployment Engine でノードが検出されるようにコンピューティングノードとストレージノードに VLAN ID を設定した場合は、 NetApp Deployment Engine でネットワークを設定する際に正しい VLAN を使用するようにしてください。

2 ノードまたは 3 ノードのストレージクラスタを使用して導入する場合は、簡易フォームを使用したあとに、「 * Network Settings * 」ページで監視ノードの IP アドレス情報を入力できます。

.手順
. オプション：このページで入力したネットワーク情報のライブ検証を無効にするには、 * ライブネットワーク検証を * スイッチを * オフ * に切り替えます。
. [ ネットワーク設定 *] ページの [ インフラストラクチャサービス *] セクションで、次のフィールドに NetApp HCI の DNS および NTP サーバ情報を入力します。
+
|===
| フィールド | 製品説明 


| * DNS サーバー IP アドレス 1 * | NetApp HCI のプライマリ DNS サーバの IP アドレスです。vCenter の設定ページで DNS サーバを指定した場合は、このフィールドが設定され、読み取り専用になります。 


| * DNS サーバー IP アドレス 2 （オプション） * | NetApp HCI のセカンダリ DNS サーバのオプションの IP アドレスです。 


| * NTP サーバーアドレス 1 * | このインフラのプライマリ NTP サーバの IP アドレスまたは完全修飾ドメイン名です。 


| * NTP サーバアドレス 2 （オプション） * | このインフラのセカンダリ NTP サーバのオプションの IP アドレスまたは完全修飾ドメイン名です。 
|===
. *を選択して時間を節約し、簡易フォーム*を起動して入力するネットワーク設定を減らします。
+
[ * ネットワーク設定簡易フォーム * ] ダイアログボックスが表示されます。

. [ 名前のプレフィックス * （ * Naming Prefix * ） ] フィールドに名前のプレフィックスを入力します。
+
この命名プレフィックスは、各ホストの名前およびストレージクラスタの名前に適用されます。プレフィックスの命名には、次のような特徴があります。

+
** 1 文字目はアルファベットにする必要があります
** アルファベット、数字、およびハイフンを使用できます
** 55 文字以内にする必要があります


. VLAN ID を割り当てるには、次のいずれかのオプションを選択します。
+
フォームを使用しているときはいつでも、行の横にある* Clear *を選択して、フィールドの行から入力をクリアします。

+

NOTE: VLAN ID を割り当てる場合は、 NetApp HCI がネットワークトラフィックに適用する VLAN タグを設定します。ネイティブ VLAN を VLAN ID として入力する必要はありません。ネットワークにネイティブ VLAN を使用する場合は、該当するフィールドを空のままにしておきます。

+
|===
| オプション | 手順 


| VLAN ID を割り当てます  a| 
.. [* VLAN ID*] オプションには、 [* Yes* ] を選択します。
.. [* VLAN ID*] 列に、 VLAN に割り当てるネットワークトラフィックのタイプごとに使用する VLAN タグを入力します。
+
コンピューティング vMotion トラフィックと iSCSI トラフィックはどちらも、共有されていない VLAN ID を使用する必要があります。

.. 「 * 次へ * 」を選択します。
.. [ * サブネット * ] 列に、各ネットワークのネットワークトラフィックのタイプごとに CIDR 形式でサブネット定義を入力します。たとえば、 192.168.1.0/24 のように入力します。
.. [ * デフォルトゲートウェイ * ] 列に、各ネットワークのネットワークトラフィックの種類ごとに、デフォルトゲートウェイの IP アドレスを入力します。
.. [* Starting IP*] 列に、各ネットワークの各ネットワークサブネットの使用可能な最初の IP アドレスを入力します。




| VLAN ID を割り当てないでください  a| 
.. [VLAN ID*] オプションに [*No*] を選択します。
.. [ * サブネット * ] 列に、各ネットワークのネットワークトラフィックのタイプごとに CIDR 形式でサブネット定義を入力します。たとえば、 192.168.1.0/24 のように入力します。
.. [ * デフォルトゲートウェイ * ] 列に、各ネットワークのネットワークトラフィックの種類ごとに、デフォルトゲートウェイの IP アドレスを入力します。
.. [*Starting IP*] 列に、各ネットワークの各タイプのネットワークトラフィックに対して使用可能な最初の IP アドレスを入力します。


|===
. [ネットワーク設定に適用]*を選択します。
. 「*はい*」を選択して確定します。
+
これにより、 [ ネットワーク設定 *] ページに簡易フォームに入力した設定が表示されます。入力した IP アドレスは NetApp HCI で検証されます。この検証は、 [ ライブネットワーク検証を無効にする ] ボタンを使用して無効にできます。

. 自動的に入力されたデータが正しいことを確認します。
. 「 * Continue * 」を選択します。




== 詳細情報

* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 向け NetApp Element プラグイン"^]
* https://www.netapp.com/us/documentation/hci.aspx["NetApp HCI のリソースページ"^]
* http://docs.netapp.com/sfe-122/index.jsp["SolidFire と Element ソフトウェアドキュメントセンター"^]

