---
sidebar: sidebar 
permalink: docs/task_mnode_enable_activeIQ.html 
summary: 管理ノード（ mNode ）を使用して、 NetApp Active IQ と NetApp HCI テレメトリを有効にすることができます。 
keywords: netapp, hci, api, enable, active iq, activeiq, hci monitoring 
---
= Active IQ と NetApp HCI の監視を有効にします
:allow-uri-read: 


[role="lead"]
インストールまたはアップグレード時にActive IQ ストレージの監視を有効にしていない場合、NetApp HCI とNetApp HCI のコンピューティング監視を有効にすることができます。NetApp HCI Deployment Engineを使用してテレメトリを無効にした場合、この手順 の使用が必要になることがあります。

Active IQ コレクタサービスは、履歴データのレポートおよびほぼリアルタイムのパフォーマンス監視用に、設定データと Element ソフトウェアベースのクラスタパフォーマンス指標を NetApp Active IQ に転送します。NetApp HCI 監視サービスを使用すると、ストレージクラスタのエラーを vCenter に転送してアラート通知を送信できます。

.必要なもの
* ストレージクラスタで NetApp Element ソフトウェア 11.3 以降が実行されている必要があります。
* バージョン 11.3 以降を実行する管理ノードを導入しておきます。
* インターネットにアクセスできる。Active IQ コレクタサービスをダークサイトから使用することはできません。


.手順
. インストールのベースアセット ID を取得します。
+
.. 管理ノードでインベントリサービス REST API UI を開きます。
+
[listing]
----
https://<ManagementNodeIP>/inventory/1/
----
.. 「 * Authorize * 」（認証）を選択して、次の手順を実行
+
... クラスタのユーザ名とパスワードを入力します。
... クライアントIDにと入力し `mnode-client`ます。
... セッションを開始するには、 * Authorize * を選択します。
... ウィンドウを閉じます。


.. REST API UI で、 * 一部のユーザに一時的な処理を開始 / インストール * を選択します。
.. [* 試してみてください * ] を選択します。
.. [* Execute] を選択します。
.. コード200応答本文から、インストール用のをコピーします `id`。
+
[listing, subs="+quotes"]
----
{
  "installations": [
    {
      "_links": {
        "collection": "https://10.111.211.111/inventory/1/installations",
        "self": "https://10.111.217.111/inventory/1/installations/abcd01e2-ab00-1xxx-91ee-12f111xxc7x0x"
      },
      *"id": "abcd01e2-ab00-1xxx-91ee-12f111xxc7x0x",*
----
+

NOTE: インストール環境には、インストールまたはアップグレード時に作成されたベースアセットの構成が含まれています。



. テレメータの有効化：
+
.. 管理ノードのIPアドレスに続けて次のように入力し、管理ノードのmnodeサービスAPI UIにアクセスし `/mnode`ます。
+
[listing]
----
https://<ManagementNodeIP>/mnode
----
.. 「 * Authorize * （認証）」または任意のロックアイコンを選択し、次の手順を実行します。
+
... クラスタのユーザ名とパスワードを入力します。
... クライアントIDにと入力し `mnode-client`ます。
... セッションを開始するには、 * Authorize * を選択します。
... ウィンドウを閉じます。


.. ベースアセットを設定します。
+
... PUT /assets/｛ asset_id ｝ * を選択します。
... [* 試してみてください * ] を選択します。
... JSON ペイロードに次のコマンドを入力します。
+
[listing]
----
{
"telemetry_active": true
"config": {}
}
----
... 前の手順のベース ID を * asset_ID * に入力します。
... [* Execute] を選択します。
+
Active IQ サービスは、アセットが変更されるたびに自動的に再起動されます。アセットを変更すると、設定が適用されるまで短時間の遅延が発生します。





. 管理ノードの既知のアセットに、 NetApp HCI 監視用の vCenter コントローラアセット（ NetApp HCI インストールのみ）と Hybrid Cloud Control 用の vCenter コントローラアセット（すべてのインストール環境）を追加しておきます。
+

NOTE: NetApp HCI 監視サービスにはコントローラアセットが必要です。

+
.. コントローラサブアセットを追加する場合は、「 * POST /assets/｛ asset_id ｝ /controllers * 」を選択します。
.. [* 試してみてください * ] を選択します。
.. クリップボードにコピーした親ベースアセットの ID を * asset_id * フィールドに入力します。
.. 必要なペイロード値をAS `vCenter`およびvCenterクレデンシャルとともに入力し `type`ます。
+
[listing]
----
{
"username": "string",
"password": "string",
"ip": "string",
"type": "vCenter",
"host_name": "string",
"config": {}
}
----
+

NOTE: `ip`はvCenterのIPアドレスです。

.. [* Execute] を選択します。




[discrete]
== 詳細情報

* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 向け NetApp Element プラグイン"^]
* https://www.netapp.com/hybrid-cloud/hci-documentation/["NetApp HCI のリソースページ"^]

